[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.mem]]

[[inputs.system]]

#Comment out OPC UA temporarily until InfluxDB works
[[inputs.opcua]]
  endpoint = "opc.tcp://host.docker.internal:4840"
  security_policy = "None"
  security_mode = "None"
  
#   [[inputs.opcua.nodes]]
#     name = "Objects"
#     namespace = "5"
#     identifier_type = "s"
#     identifier = "::Program1:tatu"

  # Browse and collect ALL child nodes under ::Program1:tatu
  [[inputs.opcua.nodes]]
    name = "Program1_tatu"
    namespace = "5"
    identifier_type = "s"
    identifier = "::Program1"

  [[inputs.opcua.nodes]]
    name = "Mir_array_0"
    namespace = "5"
    identifier_type = "s"
    identifier = "::Program1:Mir_array.arr"
  [[inputs.opcua.nodes]]
    name = "transform"
    namespace = "5"
    identifier_type = "s"
    identifier = "::Program1:transform"
  [[inputs.opcua.nodes]]
    name = "mouse"
    namespace = "5"
    identifier_type = "s"
    identifier = "::Program1:mouse"
[[inputs.opcua.nodes]]
name = "x_screen"
namespace = "5"
identifier_type = "s"
identifier = "::Program1:mouse.x_screen"

[[inputs.opcua.nodes]]
name = "y_screen"
namespace = "5"
identifier_type = "s"
identifier = "::Program1:mouse.y_screen"

[[inputs.opcua.nodes]]
name = "x_world"
namespace = "5"
identifier_type = "s"
identifier = "::Program1:mouse.x_world"

[[inputs.opcua.nodes]]
name = "y_world"
namespace = "5"
identifier_type = "s"
identifier = "::Program1:mouse.y_world"

 
  # [[inputs.opcua.nodes]]
  #   name = "Mir_array_1"
  #   namespace = "5"
  #   identifier_type = "s"
  #   identifier = "::Program1:Mir_array.arr.[1]"

  # [[inputs.opcua.nodes]]
  #   name = "Mir_array_2"
  #   namespace = "5"
  #   identifier_type = "s"
  #   identifier = "::Program1:Mir_array.arr.[2]"

  # [[inputs.opcua.nodes]]
  #   name = "Mir_array_3"
  #   namespace = "5"
  #   identifier_type = "s"
  #   identifier = "::Program1:Mir_array.arr.[3]"

  # [[inputs.opcua.nodes]]
  #   name = "Mir_array_4"
  #   namespace = "5"
  #   identifier_type = "s"
  #   identifier = "::Program1:Mir_array.arr.[4]"

  # [[inputs.opcua.nodes]]
  #   name = "Mir_array_5"
  #   namespace = "5"
  #   identifier_type = "s"
  #   identifier = "::Program1:Mir_array.arr.[5]"

  # [[inputs.opcua.nodes]]
  #   name = "Mir_array_6"
  #   namespace = "5"
  #   identifier_type = "s"
  #   identifier = "::Program1:Mir_array.arr.[6]"

  # [[inputs.opcua.nodes]]
  #   name = "Mir_array_7"
  #   namespace = "5"
  #   identifier_type = "s"
  #   identifier = "::Program1:Mir_array.arr.[7]"

  # [[inputs.opcua.nodes]]
  #   name = "Mir_array_8"
  #   namespace = "5"
  #   identifier_type = "s"
  #   identifier = "::Program1:Mir_array.arr.[8]"