[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.mem]]

[[inputs.system]]

#Comment out OPC UA temporarily until InfluxDB works
[[inputs.opcua]]
  endpoint = "opc.tcp://host.docker.internal:4840"
  security_policy = "None"
  security_mode = "None"
  

## Copy Nodes + Rename to telegraf.conf