[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.mem]]

[[inputs.system]]

#Comment out OPC UA temporarily until InfluxDB works
[[inputs.opcua]]
  endpoint = "opc.tcp://host.docker.internal:4840"
  security_policy = "None"
  security_mode = "None"
  
#GENERATED NODES
[[inputs.opcua.nodes]]
name = "clearTransform"
namespace = "5"
identifier_type = "s"
identifier = "::Program1:clearTransform"

[[inputs.opcua.nodes]]
name = "screen_x"
namespace = "5"
identifier_type = "s"
identifier = "::Program1:screen_x"

[[inputs.opcua.nodes]]
name = "screen_y"
namespace = "5"
identifier_type = "s"
identifier = "::Program1:screen_y"

[[inputs.opcua.nodes]]
name = "size"
namespace = "5"
identifier_type = "s"
identifier = "::Program1:size"

[[inputs.opcua.nodes]]
name = "sizeNew"
namespace = "5"
identifier_type = "s"
identifier = "::Program1:sizeNew"

[[inputs.opcua.nodes]]
name = "sizeNew2"
namespace = "5"
identifier_type = "s"
identifier = "::Program1:sizeNew2"

[[inputs.opcua.nodes]]
name = "sizeOriginal"
namespace = "5"
identifier_type = "s"
identifier = "::Program1:sizeOriginal"

[[inputs.opcua.nodes]]
name = "sizeOriginal2"
namespace = "5"
identifier_type = "s"
identifier = "::Program1:sizeOriginal2"

[[inputs.opcua.nodes]]
name = "tatu"
namespace = "5"
identifier_type = "s"
identifier = "::Program1:tatu"

[[inputs.opcua.nodes]]
name = "updatetransform"
namespace = "5"
identifier_type = "s"
identifier = "::Program1:updatetransform"

[[inputs.opcua.nodes]]
name = "updateTransform"
namespace = "5"
identifier_type = "s"
identifier = "::Program1:updateTransform"

