#include "mirua_to_string.h"

#include <open62541/types.h>
#include <stdint.h>
const char* mirua_str_node_class(UA_NodeClass nodeClass) {
    switch (nodeClass) {
        case UA_NODECLASS_UNSPECIFIED: return "Unspecified";
        case UA_NODECLASS_OBJECT: return "Object";
        case UA_NODECLASS_VARIABLE: return "Variable";
        case UA_NODECLASS_METHOD: return "Method";
        case UA_NODECLASS_OBJECTTYPE: return "ObjectType";
        case UA_NODECLASS_VARIABLETYPE: return "VariableType";
        case UA_NODECLASS_REFERENCETYPE: return "ReferenceType";
        case UA_NODECLASS_DATATYPE: return "DataType";
        case UA_NODECLASS_VIEW: return "View";
        default: return "Unknown";
    }
}
const char* mirua_str_status_code(uint32_t code) {
    switch (code) {
        case 0x00000400: return "UA_STATUSCODE_INFOTYPE_DATAVALUE";
        case 0x00000080: return "UA_STATUSCODE_INFOBITS_OVERFLOW";
        case 0x00000000: return "UA_STATUSCODE_GOOD";
        case 0x40000000: return "UA_STATUSCODE_UNCERTAIN";
        case 0x80000000: return "UA_STATUSCODE_BAD";
        case 0x80010000: return "UA_STATUSCODE_BADUNEXPECTEDERROR";
        case 0x80020000: return "UA_STATUSCODE_BADINTERNALERROR";
        case 0x80030000: return "UA_STATUSCODE_BADOUTOFMEMORY";
        case 0x80040000: return "UA_STATUSCODE_BADRESOURCEUNAVAILABLE";
        case 0x80050000: return "UA_STATUSCODE_BADCOMMUNICATIONERROR";
        case 0x80060000: return "UA_STATUSCODE_BADENCODINGERROR";
        case 0x80070000: return "UA_STATUSCODE_BADDECODINGERROR";
        case 0x80080000: return "UA_STATUSCODE_BADENCODINGLIMITSEXCEEDED";
        case 0x80B80000: return "UA_STATUSCODE_BADREQUESTTOOLARGE";
        case 0x80B90000: return "UA_STATUSCODE_BADRESPONSETOOLARGE";
        case 0x80090000: return "UA_STATUSCODE_BADUNKNOWNRESPONSE";
        case 0x800A0000: return "UA_STATUSCODE_BADTIMEOUT";
        case 0x800B0000: return "UA_STATUSCODE_BADSERVICEUNSUPPORTED";
        case 0x800C0000: return "UA_STATUSCODE_BADSHUTDOWN";
        case 0x800D0000: return "UA_STATUSCODE_BADSERVERNOTCONNECTED";
        case 0x800E0000: return "UA_STATUSCODE_BADSERVERHALTED";
        case 0x800F0000: return "UA_STATUSCODE_BADNOTHINGTODO";
        case 0x80100000: return "UA_STATUSCODE_BADTOOMANYOPERATIONS";
        case 0x80DB0000: return "UA_STATUSCODE_BADTOOMANYMONITOREDITEMS";
        case 0x80110000: return "UA_STATUSCODE_BADDATATYPEIDUNKNOWN";
        case 0x80120000: return "UA_STATUSCODE_BADCERTIFICATEINVALID";
        case 0x80130000: return "UA_STATUSCODE_BADSECURITYCHECKSFAILED";
        case 0x81140000: return "UA_STATUSCODE_BADCERTIFICATEPOLICYCHECKFAILED";
        case 0x80140000: return "UA_STATUSCODE_BADCERTIFICATETIMEINVALID";
        case 0x80150000: return "UA_STATUSCODE_BADCERTIFICATEISSUERTIMEINVALID";
        case 0x80160000: return "UA_STATUSCODE_BADCERTIFICATEHOSTNAMEINVALID";
        case 0x80170000: return "UA_STATUSCODE_BADCERTIFICATEURIINVALID";
        case 0x80180000: return "UA_STATUSCODE_BADCERTIFICATEUSENOTALLOWED";
        case 0x80190000: return "UA_STATUSCODE_BADCERTIFICATEISSUERUSENOTALLOWED";
        case 0x801A0000: return "UA_STATUSCODE_BADCERTIFICATEUNTRUSTED";
        case 0x801B0000: return "UA_STATUSCODE_BADCERTIFICATEREVOCATIONUNKNOWN";
        case 0x801C0000: return "UA_STATUSCODE_BADCERTIFICATEISSUERREVOCATIONUNKNOWN";
        case 0x801D0000: return "UA_STATUSCODE_BADCERTIFICATEREVOKED";
        case 0x801E0000: return "UA_STATUSCODE_BADCERTIFICATEISSUERREVOKED";
        case 0x810D0000: return "UA_STATUSCODE_BADCERTIFICATECHAININCOMPLETE";
        case 0x801F0000: return "UA_STATUSCODE_BADUSERACCESSDENIED";
        case 0x80200000: return "UA_STATUSCODE_BADIDENTITYTOKENINVALID";
        case 0x80210000: return "UA_STATUSCODE_BADIDENTITYTOKENREJECTED";
        case 0x80220000: return "UA_STATUSCODE_BADSECURECHANNELIDINVALID";
        case 0x80230000: return "UA_STATUSCODE_BADINVALIDTIMESTAMP";
        case 0x80240000: return "UA_STATUSCODE_BADNONCEINVALID";
        case 0x80250000: return "UA_STATUSCODE_BADSESSIONIDINVALID";
        case 0x80260000: return "UA_STATUSCODE_BADSESSIONCLOSED";
        case 0x80270000: return "UA_STATUSCODE_BADSESSIONNOTACTIVATED";
        case 0x80280000: return "UA_STATUSCODE_BADSUBSCRIPTIONIDINVALID";
        case 0x802A0000: return "UA_STATUSCODE_BADREQUESTHEADERINVALID";
        case 0x802B0000: return "UA_STATUSCODE_BADTIMESTAMPSTORETURNINVALID";
        case 0x802C0000: return "UA_STATUSCODE_BADREQUESTCANCELLEDBYCLIENT";
        case 0x80E50000: return "UA_STATUSCODE_BADTOOMANYARGUMENTS";
        case 0x810E0000: return "UA_STATUSCODE_BADLICENSEEXPIRED";
        case 0x810F0000: return "UA_STATUSCODE_BADLICENSELIMITSEXCEEDED";
        case 0x81100000: return "UA_STATUSCODE_BADLICENSENOTAVAILABLE";
        case 0x002D0000: return "UA_STATUSCODE_GOODSUBSCRIPTIONTRANSFERRED";
        case 0x002E0000: return "UA_STATUSCODE_GOODCOMPLETESASYNCHRONOUSLY";
        case 0x002F0000: return "UA_STATUSCODE_GOODOVERLOAD";
        case 0x00300000: return "UA_STATUSCODE_GOODCLAMPED";
        case 0x80310000: return "UA_STATUSCODE_BADNOCOMMUNICATION";
        case 0x80320000: return "UA_STATUSCODE_BADWAITINGFORINITIALDATA";
        case 0x80330000: return "UA_STATUSCODE_BADNODEIDINVALID";
        case 0x80340000: return "UA_STATUSCODE_BADNODEIDUNKNOWN";
        case 0x80350000: return "UA_STATUSCODE_BADATTRIBUTEIDINVALID";
        case 0x80360000: return "UA_STATUSCODE_BADINDEXRANGEINVALID";
        case 0x80370000: return "UA_STATUSCODE_BADINDEXRANGENODATA";
        case 0x80380000: return "UA_STATUSCODE_BADDATAENCODINGINVALID";
        case 0x80390000: return "UA_STATUSCODE_BADDATAENCODINGUNSUPPORTED";
        case 0x803A0000: return "UA_STATUSCODE_BADNOTREADABLE";
        case 0x803B0000: return "UA_STATUSCODE_BADNOTWRITABLE";
        case 0x803C0000: return "UA_STATUSCODE_BADOUTOFRANGE";
        case 0x803D0000: return "UA_STATUSCODE_BADNOTSUPPORTED";
        case 0x803E0000: return "UA_STATUSCODE_BADNOTFOUND";
        case 0x803F0000: return "UA_STATUSCODE_BADOBJECTDELETED";
        case 0x80400000: return "UA_STATUSCODE_BADNOTIMPLEMENTED";
        case 0x80410000: return "UA_STATUSCODE_BADMONITORINGMODEINVALID";
        case 0x80420000: return "UA_STATUSCODE_BADMONITOREDITEMIDINVALID";
        case 0x80430000: return "UA_STATUSCODE_BADMONITOREDITEMFILTERINVALID";
        case 0x80440000: return "UA_STATUSCODE_BADMONITOREDITEMFILTERUNSUPPORTED";
        case 0x80450000: return "UA_STATUSCODE_BADFILTERNOTALLOWED";
        case 0x80460000: return "UA_STATUSCODE_BADSTRUCTUREMISSING";
        case 0x80470000: return "UA_STATUSCODE_BADEVENTFILTERINVALID";
        case 0x80480000: return "UA_STATUSCODE_BADCONTENTFILTERINVALID";
        case 0x80C10000: return "UA_STATUSCODE_BADFILTEROPERATORINVALID";
        case 0x80C20000: return "UA_STATUSCODE_BADFILTEROPERATORUNSUPPORTED";
        case 0x80C30000: return "UA_STATUSCODE_BADFILTEROPERANDCOUNTMISMATCH";
        case 0x80490000: return "UA_STATUSCODE_BADFILTEROPERANDINVALID";
        case 0x80C40000: return "UA_STATUSCODE_BADFILTERELEMENTINVALID";
        case 0x80C50000: return "UA_STATUSCODE_BADFILTERLITERALINVALID";
        case 0x804A0000: return "UA_STATUSCODE_BADCONTINUATIONPOINTINVALID";
        case 0x804B0000: return "UA_STATUSCODE_BADNOCONTINUATIONPOINTS";
        case 0x804C0000: return "UA_STATUSCODE_BADREFERENCETYPEIDINVALID";
        case 0x804D0000: return "UA_STATUSCODE_BADBROWSEDIRECTIONINVALID";
        case 0x804E0000: return "UA_STATUSCODE_BADNODENOTINVIEW";
        case 0x81120000: return "UA_STATUSCODE_BADNUMERICOVERFLOW";
        case 0x804F0000: return "UA_STATUSCODE_BADSERVERURIINVALID";
        case 0x80500000: return "UA_STATUSCODE_BADSERVERNAMEMISSING";
        case 0x80510000: return "UA_STATUSCODE_BADDISCOVERYURLMISSING";
        case 0x80520000: return "UA_STATUSCODE_BADSEMPAHOREFILEMISSING";
        case 0x80530000: return "UA_STATUSCODE_BADREQUESTTYPEINVALID";
        case 0x80540000: return "UA_STATUSCODE_BADSECURITYMODEREJECTED";
        case 0x80550000: return "UA_STATUSCODE_BADSECURITYPOLICYREJECTED";
        case 0x80560000: return "UA_STATUSCODE_BADTOOMANYSESSIONS";
        case 0x80570000: return "UA_STATUSCODE_BADUSERSIGNATUREINVALID";
        case 0x80580000: return "UA_STATUSCODE_BADAPPLICATIONSIGNATUREINVALID";
        case 0x80590000: return "UA_STATUSCODE_BADNOVALIDCERTIFICATES";
        case 0x80C60000: return "UA_STATUSCODE_BADIDENTITYCHANGENOTSUPPORTED";
        case 0x805A0000: return "UA_STATUSCODE_BADREQUESTCANCELLEDBYREQUEST";
        case 0x805B0000: return "UA_STATUSCODE_BADPARENTNODEIDINVALID";
        case 0x805C0000: return "UA_STATUSCODE_BADREFERENCENOTALLOWED";
        case 0x805D0000: return "UA_STATUSCODE_BADNODEIDREJECTED";
        case 0x805E0000: return "UA_STATUSCODE_BADNODEIDEXISTS";
        case 0x805F0000: return "UA_STATUSCODE_BADNODECLASSINVALID";
        case 0x80600000: return "UA_STATUSCODE_BADBROWSENAMEINVALID";
        case 0x80610000: return "UA_STATUSCODE_BADBROWSENAMEDUPLICATED";
        case 0x80620000: return "UA_STATUSCODE_BADNODEATTRIBUTESINVALID";
        case 0x80630000: return "UA_STATUSCODE_BADTYPEDEFINITIONINVALID";
        case 0x80640000: return "UA_STATUSCODE_BADSOURCENODEIDINVALID";
        case 0x80650000: return "UA_STATUSCODE_BADTARGETNODEIDINVALID";
        case 0x80660000: return "UA_STATUSCODE_BADDUPLICATEREFERENCENOTALLOWED";
        case 0x80670000: return "UA_STATUSCODE_BADINVALIDSELFREFERENCE";
        case 0x80680000: return "UA_STATUSCODE_BADREFERENCELOCALONLY";
        case 0x80690000: return "UA_STATUSCODE_BADNODELETERIGHTS";
        case 0x40BC0000: return "UA_STATUSCODE_UNCERTAINREFERENCENOTDELETED";
        case 0x806A0000: return "UA_STATUSCODE_BADSERVERINDEXINVALID";
        case 0x806B0000: return "UA_STATUSCODE_BADVIEWIDUNKNOWN";
        case 0x80C90000: return "UA_STATUSCODE_BADVIEWTIMESTAMPINVALID";
        case 0x80CA0000: return "UA_STATUSCODE_BADVIEWPARAMETERMISMATCH";
        case 0x80CB0000: return "UA_STATUSCODE_BADVIEWVERSIONINVALID";
        case 0x40C00000: return "UA_STATUSCODE_UNCERTAINNOTALLNODESAVAILABLE";
        case 0x00BA0000: return "UA_STATUSCODE_GOODRESULTSMAYBEINCOMPLETE";
        case 0x80C80000: return "UA_STATUSCODE_BADNOTTYPEDEFINITION";
        case 0x406C0000: return "UA_STATUSCODE_UNCERTAINREFERENCEOUTOFSERVER";
        case 0x806D0000: return "UA_STATUSCODE_BADTOOMANYMATCHES";
        case 0x806E0000: return "UA_STATUSCODE_BADQUERYTOOCOMPLEX";
        case 0x806F0000: return "UA_STATUSCODE_BADNOMATCH";
        case 0x80700000: return "UA_STATUSCODE_BADMAXAGEINVALID";
        case 0x80E60000: return "UA_STATUSCODE_BADSECURITYMODEINSUFFICIENT";
        case 0x80710000: return "UA_STATUSCODE_BADHISTORYOPERATIONINVALID";
        case 0x80720000: return "UA_STATUSCODE_BADHISTORYOPERATIONUNSUPPORTED";
        case 0x80BD0000: return "UA_STATUSCODE_BADINVALIDTIMESTAMPARGUMENT";
        case 0x80730000: return "UA_STATUSCODE_BADWRITENOTSUPPORTED";
        case 0x80740000: return "UA_STATUSCODE_BADTYPEMISMATCH";
        case 0x80750000: return "UA_STATUSCODE_BADMETHODINVALID";
        case 0x80760000: return "UA_STATUSCODE_BADARGUMENTSMISSING";
        case 0x81110000: return "UA_STATUSCODE_BADNOTEXECUTABLE";
        case 0x80770000: return "UA_STATUSCODE_BADTOOMANYSUBSCRIPTIONS";
        case 0x80780000: return "UA_STATUSCODE_BADTOOMANYPUBLISHREQUESTS";
        case 0x80790000: return "UA_STATUSCODE_BADNOSUBSCRIPTION";
        case 0x807A0000: return "UA_STATUSCODE_BADSEQUENCENUMBERUNKNOWN";
        case 0x00DF0000: return "UA_STATUSCODE_GOODRETRANSMISSIONQUEUENOTSUPPORTED";
        case 0x807B0000: return "UA_STATUSCODE_BADMESSAGENOTAVAILABLE";
        case 0x807C0000: return "UA_STATUSCODE_BADINSUFFICIENTCLIENTPROFILE";
        case 0x80BF0000: return "UA_STATUSCODE_BADSTATENOTACTIVE";
        case 0x81150000: return "UA_STATUSCODE_BADALREADYEXISTS";
        case 0x807D0000: return "UA_STATUSCODE_BADTCPSERVERTOOBUSY";
        case 0x807E0000: return "UA_STATUSCODE_BADTCPMESSAGETYPEINVALID";
        case 0x807F0000: return "UA_STATUSCODE_BADTCPSECURECHANNELUNKNOWN";
        case 0x80800000: return "UA_STATUSCODE_BADTCPMESSAGETOOLARGE";
        case 0x80810000: return "UA_STATUSCODE_BADTCPNOTENOUGHRESOURCES";
        case 0x80820000: return "UA_STATUSCODE_BADTCPINTERNALERROR";
        case 0x80830000: return "UA_STATUSCODE_BADTCPENDPOINTURLINVALID";
        case 0x80840000: return "UA_STATUSCODE_BADREQUESTINTERRUPTED";
        case 0x80850000: return "UA_STATUSCODE_BADREQUESTTIMEOUT";
        case 0x80860000: return "UA_STATUSCODE_BADSECURECHANNELCLOSED";
        case 0x80870000: return "UA_STATUSCODE_BADSECURECHANNELTOKENUNKNOWN";
        case 0x80880000: return "UA_STATUSCODE_BADSEQUENCENUMBERINVALID";
        case 0x80BE0000: return "UA_STATUSCODE_BADPROTOCOLVERSIONUNSUPPORTED";
        case 0x80890000: return "UA_STATUSCODE_BADCONFIGURATIONERROR";
        case 0x808A0000: return "UA_STATUSCODE_BADNOTCONNECTED";
        case 0x808B0000: return "UA_STATUSCODE_BADDEVICEFAILURE";
        case 0x808C0000: return "UA_STATUSCODE_BADSENSORFAILURE";
        case 0x808D0000: return "UA_STATUSCODE_BADOUTOFSERVICE";
        case 0x808E0000: return "UA_STATUSCODE_BADDEADBANDFILTERINVALID";
        case 0x408F0000: return "UA_STATUSCODE_UNCERTAINNOCOMMUNICATIONLASTUSABLEVALUE";
        case 0x40900000: return "UA_STATUSCODE_UNCERTAINLASTUSABLEVALUE";
        case 0x40910000: return "UA_STATUSCODE_UNCERTAINSUBSTITUTEVALUE";
        case 0x40920000: return "UA_STATUSCODE_UNCERTAININITIALVALUE";
        case 0x40930000: return "UA_STATUSCODE_UNCERTAINSENSORNOTACCURATE";
        case 0x40940000: return "UA_STATUSCODE_UNCERTAINENGINEERINGUNITSEXCEEDED";
        case 0x40950000: return "UA_STATUSCODE_UNCERTAINSUBNORMAL";
        case 0x00960000: return "UA_STATUSCODE_GOODLOCALOVERRIDE";
        case 0x80970000: return "UA_STATUSCODE_BADREFRESHINPROGRESS";
        case 0x80980000: return "UA_STATUSCODE_BADCONDITIONALREADYDISABLED";
        case 0x80CC0000: return "UA_STATUSCODE_BADCONDITIONALREADYENABLED";
        case 0x80990000: return "UA_STATUSCODE_BADCONDITIONDISABLED";
        case 0x809A0000: return "UA_STATUSCODE_BADEVENTIDUNKNOWN";
        case 0x80BB0000: return "UA_STATUSCODE_BADEVENTNOTACKNOWLEDGEABLE";
        case 0x80CD0000: return "UA_STATUSCODE_BADDIALOGNOTACTIVE";
        case 0x80CE0000: return "UA_STATUSCODE_BADDIALOGRESPONSEINVALID";
        case 0x80CF0000: return "UA_STATUSCODE_BADCONDITIONBRANCHALREADYACKED";
        case 0x80D00000: return "UA_STATUSCODE_BADCONDITIONBRANCHALREADYCONFIRMED";
        case 0x80D10000: return "UA_STATUSCODE_BADCONDITIONALREADYSHELVED";
        case 0x80D20000: return "UA_STATUSCODE_BADCONDITIONNOTSHELVED";
        case 0x80D30000: return "UA_STATUSCODE_BADSHELVINGTIMEOUTOFRANGE";
        case 0x809B0000: return "UA_STATUSCODE_BADNODATA";
        case 0x80D70000: return "UA_STATUSCODE_BADBOUNDNOTFOUND";
        case 0x80D80000: return "UA_STATUSCODE_BADBOUNDNOTSUPPORTED";
        case 0x809D0000: return "UA_STATUSCODE_BADDATALOST";
        case 0x809E0000: return "UA_STATUSCODE_BADDATAUNAVAILABLE";
        case 0x809F0000: return "UA_STATUSCODE_BADENTRYEXISTS";
        case 0x80A00000: return "UA_STATUSCODE_BADNOENTRYEXISTS";
        case 0x80A10000: return "UA_STATUSCODE_BADTIMESTAMPNOTSUPPORTED";
        case 0x00A20000: return "UA_STATUSCODE_GOODENTRYINSERTED";
        case 0x00A30000: return "UA_STATUSCODE_GOODENTRYREPLACED";
        case 0x40A40000: return "UA_STATUSCODE_UNCERTAINDATASUBNORMAL";
        case 0x00A50000: return "UA_STATUSCODE_GOODNODATA";
        case 0x00A60000: return "UA_STATUSCODE_GOODMOREDATA";
        case 0x80D40000: return "UA_STATUSCODE_BADAGGREGATELISTMISMATCH";
        case 0x80D50000: return "UA_STATUSCODE_BADAGGREGATENOTSUPPORTED";
        case 0x80D60000: return "UA_STATUSCODE_BADAGGREGATEINVALIDINPUTS";
        case 0x80DA0000: return "UA_STATUSCODE_BADAGGREGATECONFIGURATIONREJECTED";
        case 0x00D90000: return "UA_STATUSCODE_GOODDATAIGNORED";
        case 0x80E40000: return "UA_STATUSCODE_BADREQUESTNOTALLOWED";
        case 0x81130000: return "UA_STATUSCODE_BADREQUESTNOTCOMPLETE";
        case 0x811F0000: return "UA_STATUSCODE_BADTICKETREQUIRED";
        case 0x81200000: return "UA_STATUSCODE_BADTICKETINVALID";
        case 0x00DC0000: return "UA_STATUSCODE_GOODEDITED";
        case 0x00DD0000: return "UA_STATUSCODE_GOODPOSTACTIONFAILED";
        case 0x40DE0000: return "UA_STATUSCODE_UNCERTAINDOMINANTVALUECHANGED";
        case 0x00E00000: return "UA_STATUSCODE_GOODDEPENDENTVALUECHANGED";
        case 0x80E10000: return "UA_STATUSCODE_BADDOMINANTVALUECHANGED";
        case 0x40E20000: return "UA_STATUSCODE_UNCERTAINDEPENDENTVALUECHANGED";
        case 0x80E30000: return "UA_STATUSCODE_BADDEPENDENTVALUECHANGED";
        case 0x01160000: return "UA_STATUSCODE_GOODEDITED_DEPENDENTVALUECHANGED";
        case 0x01170000: return "UA_STATUSCODE_GOODEDITED_DOMINANTVALUECHANGED";
        case 0x01180000:
            return "UA_STATUSCODE_GOODEDITED_DOMINANTVALUECHANGED_DEPENDENTVALUECHANGED";
        case 0x81190000: return "UA_STATUSCODE_BADEDITED_OUTOFRANGE";
        case 0x811A0000: return "UA_STATUSCODE_BADINITIALVALUE_OUTOFRANGE";
        case 0x811B0000: return "UA_STATUSCODE_BADOUTOFRANGE_DOMINANTVALUECHANGED";
        case 0x811C0000: return "UA_STATUSCODE_BADEDITED_OUTOFRANGE_DOMINANTVALUECHANGED";
        case 0x811D0000:
            return "UA_STATUSCODE_BADOUTOFRANGE_DOMINANTVALUECHANGED_DEPENDENTVALUECHANGED";
        case 0x811E0000:
            return "UA_STATUSCODE_BADEDITED_OUTOFRANGE_DOMINANTVALUECHANGED_DEPENDENTVALUECHANGED";
        case 0x00A70000: return "UA_STATUSCODE_GOODCOMMUNICATIONEVENT";
        case 0x00A80000: return "UA_STATUSCODE_GOODSHUTDOWNEVENT";
        case 0x00A90000: return "UA_STATUSCODE_GOODCALLAGAIN";
        case 0x00AA0000: return "UA_STATUSCODE_GOODNONCRITICALTIMEOUT";
        case 0x80AB0000: return "UA_STATUSCODE_BADINVALIDARGUMENT";
        case 0x80AC0000: return "UA_STATUSCODE_BADCONNECTIONREJECTED";
        case 0x80AD0000: return "UA_STATUSCODE_BADDISCONNECT";
        case 0x80AE0000: return "UA_STATUSCODE_BADCONNECTIONCLOSED";
        case 0x80AF0000: return "UA_STATUSCODE_BADINVALIDSTATE";
        case 0x80B00000: return "UA_STATUSCODE_BADENDOFSTREAM";
        case 0x80B10000: return "UA_STATUSCODE_BADNODATAAVAILABLE";
        case 0x80B20000: return "UA_STATUSCODE_BADWAITINGFORRESPONSE";
        case 0x80B30000: return "UA_STATUSCODE_BADOPERATIONABANDONED";
        case 0x80B40000: return "UA_STATUSCODE_BADEXPECTEDSTREAMTOBLOCK";
        case 0x80B50000: return "UA_STATUSCODE_BADWOULDBLOCK";
        case 0x80B60000: return "UA_STATUSCODE_BADSYNTAXERROR";
        case 0x80B70000: return "UA_STATUSCODE_BADMAXCONNECTIONSREACHED";
        default: return "Unknown StatusCode";
    }
}

const char* mirua_str_secure_channel_state(UA_SecureChannelState state) {
    switch (state) {
        case UA_SECURECHANNELSTATE_CLOSED: return "UA_SECURECHANNELSTATE_CLOSED";
        case UA_SECURECHANNELSTATE_REVERSE_LISTENING:
            return "UA_SECURECHANNELSTATE_REVERSE_LISTENING";
        case UA_SECURECHANNELSTATE_CONNECTING: return "UA_SECURECHANNELSTATE_CONNECTING";
        case UA_SECURECHANNELSTATE_CONNECTED: return "UA_SECURECHANNELSTATE_CONNECTED";
        case UA_SECURECHANNELSTATE_REVERSE_CONNECTED:
            return "UA_SECURECHANNELSTATE_REVERSE_CONNECTED";
        case UA_SECURECHANNELSTATE_RHE_SENT: return "UA_SECURECHANNELSTATE_RHE_SENT";
        case UA_SECURECHANNELSTATE_HEL_SENT: return "UA_SECURECHANNELSTATE_HEL_SENT";
        case UA_SECURECHANNELSTATE_HEL_RECEIVED: return "UA_SECURECHANNELSTATE_HEL_RECEIVED";
        case UA_SECURECHANNELSTATE_ACK_SENT: return "UA_SECURECHANNELSTATE_ACK_SENT";
        case UA_SECURECHANNELSTATE_ACK_RECEIVED: return "UA_SECURECHANNELSTATE_ACK_RECEIVED";
        case UA_SECURECHANNELSTATE_OPN_SENT: return "UA_SECURECHANNELSTATE_OPN_SENT";
        case UA_SECURECHANNELSTATE_OPEN: return "UA_SECURECHANNELSTATE_OPEN";
        case UA_SECURECHANNELSTATE_CLOSING: return "UA_SECURECHANNELSTATE_CLOSING";
        default: return "Unknown UA_SecureChannelState";
    }
}

const char* mirua_str_session_state(UA_SessionState state) {
    switch (state) {
        case UA_SESSIONSTATE_CLOSED: return "UA_SESSIONSTATE_CLOSED";
        case UA_SESSIONSTATE_CREATE_REQUESTED: return "UA_SESSIONSTATE_CREATE_REQUESTED";
        case UA_SESSIONSTATE_CREATED: return "UA_SESSIONSTATE_CREATED";
        case UA_SESSIONSTATE_ACTIVATE_REQUESTED: return "UA_SESSIONSTATE_ACTIVATE_REQUESTED";
        case UA_SESSIONSTATE_ACTIVATED: return "UA_SESSIONSTATE_ACTIVATED";
        case UA_SESSIONSTATE_CLOSING: return "UA_SESSIONSTATE_CLOSING";
        default: return "Unknown UA_SessionState";
    }
}

const char* mirua_to_string_attribute_id(uint32_t attrId) {
    switch (attrId) {
        case 1: return "NodeId";
        case 2: return "NodeClass";
        case 3: return "BrowseName";
        case 4: return "DisplayName";
        case 5: return "Description";
        case 6: return "WriteMask";
        case 7: return "UserWriteMask";
        case 8: return "IsAbstract";
        case 9: return "Symmetric";
        case 10: return "InverseName";
        case 11: return "ContainsNoLoops";
        case 12: return "EventNotifier";
        case 13: return "Value";
        case 14: return "DataType";
        case 15: return "ValueRank";
        case 16: return "ArrayDimensions";
        case 17: return "AccessLevel";
        case 18: return "UserAccessLevel";
        case 19: return "MinimumSamplingInterval";
        case 20: return "Historizing";
        case 21: return "Executable";
        case 22: return "UserExecutable";
        case 23: return "DataTypeDefinition";
        case 24: return "RolePermissions";
        case 25: return "UserRolePermissions";
        case 26: return "AccessRestrictions";
        case 27: return "AccessLevelEx";
        default: return "Unknown AttributeId";
    }
}

int mirua_to_string_ua_variant(char* buf, const UA_Variant* val) {
    (void)buf;
    (void)val;

    return 0;
}
